const json=(status,body,extra={})=>({status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,PUT,OPTIONS','Access-Control-Allow-Headers':'Content-Type',...extra},body:JSON.stringify(body)});
const gh=async(method,env,body)=>{const url=`https://api.github.com/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/contents/${env.GITHUB_CONFIG_PATH||'config.json'}`+(method==='GET'?`?ref=${encodeURIComponent(env.GITHUB_BRANCH||'main')}`:'');return fetch(url,{method,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${env.GITHUB_TOKEN}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined})};
const b64=s=>Buffer.from(s,'utf8').toString('base64');
const from64=s=>Buffer.from(s.replace(/\n/g,''),'base64').toString('utf8');
export default async req=>{if(req.httpMethod==='OPTIONS')return json(204,{});
const env=process.env;
if(req.httpMethod==='GET'){try{const r=await gh('GET',env);if(!r.ok)return json(502,{error:'GitHub read failed'});const x=await r.json();const d=JSON.parse(from64(x.content));return json(200,{enabled:d.enabled===true,destinationUrl:typeof d.destinationUrl==='string'?d.destinationUrl:'',updatedAt:d.updatedAt||null})}catch{return json(502,{error:'Configuration unavailable'})}}
if(req.httpMethod==='POST'){try{const b=JSON.parse(req.body||'{}');if(b.action!=='login'||!b.password||b.password!==env.ADMIN_PASSWORD)return json(401,{error:'Unauthorized'});return json(200,{ok:true})}catch{return json(400,{error:'Bad request'})}}
if(req.httpMethod==='PUT'){try{const b=JSON.parse(req.body||'{}');if(!b.password||b.password!==env.ADMIN_PASSWORD)return json(401,{error:'Unauthorized'});if(typeof b.enabled!=='boolean')return json(400,{error:'enabled must be boolean'});let u;try{u=new URL(b.destinationUrl);if(!['http:','https:'].includes(u.protocol))throw Error()}catch{return json(400,{error:'Invalid destination URL'})}const current=await gh('GET',env);if(!current.ok)return json(502,{error:'GitHub read failed'});const cur=await current.json();const content=b64(JSON.stringify({enabled:b.enabled,destinationUrl:b.destinationUrl.trim(),updatedAt:new Date().toISOString()},null,2)+'\n');const r=await gh('PUT',env,{message:'Update redirect configuration',content,sha:cur.sha,branch:env.GITHUB_BRANCH||'main'});if(!r.ok)return json(502,{error:'GitHub write failed'});return json(200,{ok:true})}catch{return json(500,{error:'Server error'})}}
return json(405,{error:'Method not allowed'})};
